name: gluon
dependencies:
- python=3.6
- pip:
  - mxnet==1.5.0
  - d2lzh==0.8.11
  - jupyter==1.0.0
  - matplotlib==2.2.2
  - pandas==0.23.4
  - scipy==1.3.1
  - torch==1.1.0
  - torchvision==0.3.0
  - tqdm==4.36.1
  - opencv-python==4.1.1.26
